import { Routes } from '@angular/router';
import { AuthGuard } from './core/auth.guard';
import { PermisosGuard } from './core/permisos.guard';

export const routes: Routes = [

  // ==================================================================
  // Transversales
  // ==================================================================
  { path: '', redirectTo: 'login', pathMatch: 'full' },
  { path: 'configuracion', loadComponent: () => import('./components/configuracion/configuracion.component').then(m => m.ConfiguracionComponent), canActivate: [AuthGuard] },
  { path: 'login', loadComponent: () => import('./components/login/login.component').then(m => m.LoginComponent) },
  { path: 'menu', loadComponent: () => import('./components/menu/menu.component').then(m => m.MenuComponent), canActivate: [AuthGuard] },
  { path: 'mi-perfil', loadComponent: () => import('./components/mi-perfil/mi-perfil.component').then(m => m.MiPerfilComponent), canActivate: [AuthGuard] },
  { path: 'registro', loadComponent: () => import('./components/registro/registro.component').then(m => m.RegistroComponent), canActivate: [AuthGuard] },
  { path: 'registro-ingreso-salida', loadComponent: () => import('./components/colaboradores/registro-ingreso-salida/registro-ingreso-salida.component').then(m => m.RegistroIngresoSalidaComponent), canActivate: [AuthGuard] },
  { path: 'salir', loadComponent: () => import('./components/login/login.component').then(m => m.LoginComponent) },
  { path: 'usuarios', redirectTo: 'administracion/datos-maestros/usuarios', pathMatch: 'full' },

  // ==================================================================
  // Estudiantes
  // ==================================================================
  { path: 'estudiantes/gestion', loadComponent: () => import('./components/estudiantes/gestion-estudiantes/gestion-estudiantes.component').then(m => m.GestionEstudiantesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'estudiantes.gestion', trackear: true, labelAcceso: 'Gestión Estudiantes', iconoAcceso: '🎓' } },
  { path: 'estudiantes/registro-rapido', loadComponent: () => import('./components/estudiantes/registro-rapido-estudiante/registro-rapido-estudiante.component').then(m => m.RegistroRapidoEstudianteComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'estudiantes.administrar' } },
  { path: 'estudiantes', loadComponent: () => import('./components/estudiantes/estudiantes.component').then(m => m.EstudiantesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'estudiantes.listado', trackear: true, labelAcceso: 'Estudiantes', iconoAcceso: '🎓' } },
  { path: 'estudiantes/pagos/comprobante/:id', loadComponent: () => import('./components/estudiantes/pagos/comprobante-pago/comprobante-pago-view.component').then(m => m.ComprobantePagoViewComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'estudiantes.pagos' } },
  { path: 'estudiantes/acudientes/:accion/:id/:idEstudiante', loadComponent: () => import('./components/estudiantes/acudientes/crear-acudiente/crear-acudiente.component').then(m => m.CrearAcudienteComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'estudiantes.acudientes.administrar' } },
  { path: 'estudiantes/acudientes/:id', loadComponent: () => import('./components/estudiantes/acudientes/acudientes.component').then(m => m.AcudientesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'estudiantes.acudientes' } },
  { path: 'estudiantes/contratos/:accion/:id/:idEstudiante', loadComponent: () => import('./components/estudiantes/contratos-estudiantes/crear-contrato/crear-contrato.component').then(m => m.CrearContratoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'estudiantes.contratos.administrar' } },
  { path: 'estudiantes/contratos/:id', loadComponent: () => import('./components/estudiantes/contratos-estudiantes/contratos-estudiantes.component').then(m => m.ContratosEstudiantesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'estudiantes.contratos' } },
  { path: 'estudiantes/cursos-extra/:accion/:id/:idEstudiante', loadComponent: () => import('./components/estudiantes/cursos-extra-estudiante/crear-curso-extra-estudiante/crear-curso-extra-estudiante.component').then(m => m.CrearCursoExtraEstudianteComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'estudiantes.listado' } },
  { path: 'estudiantes/cursos-extra/:id', loadComponent: () => import('./components/estudiantes/cursos-extra-estudiante/cursos-extra-estudiante.component').then(m => m.CursosExtraEstudianteComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'estudiantes.listado' } },
  { path: 'estudiantes/medidas/:accion/:id/:idEstudiante', loadComponent: () => import('./components/estudiantes/medidas/crear-medidas/crear-medidas.component').then(m => m.CrearMedidasComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'estudiantes.medidas.administrar' } },
  { path: 'estudiantes/medidas/:id', loadComponent: () => import('./components/estudiantes/medidas/medidas-estudiantes.component').then(m => m.MedidasEstudiantesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'estudiantes.medidas' } },
  { path: 'estudiantes/observaciones/:accion/:id/:idEstudiante', loadComponent: () => import('./components/estudiantes/observaciones/crear-observaciones/crear-observaciones.component').then(m => m.CrearObservacionesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'estudiantes.observaciones.administrar' } },
  { path: 'estudiantes/observaciones/:id', loadComponent: () => import('./components/estudiantes/observaciones/observaciones-estudiantes.component').then(m => m.ObservacionesEstudiantesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'estudiantes.observaciones' } },
  { path: 'estudiantes/onces/:accion/:id/:idEstudiante', loadComponent: () => import('./components/estudiantes/onces-alimentacion/crear-onces-alimentacion/crear-onces-alimentacion.component').then(m => m.CrearOncesAlimentacionComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'estudiantes.onces.administrar' } },
  { path: 'estudiantes/onces/:id', loadComponent: () => import('./components/estudiantes/onces-alimentacion/onces-alimentacion.component').then(m => m.OncesAlimentacionComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'estudiantes.onces' } },
  { path: 'estudiantes/opciones/:id', loadComponent: () => import('./components/estudiantes/opciones-estudiante/opciones-estudiante.component').then(m => m.OpcionesEstudianteComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'estudiantes.listado' } },
  { path: 'estudiantes/pagos/:accion/:id/:idEstudiante', loadComponent: () => import('./components/estudiantes/pagos/crear-pagos-recibidos/crear-pagos-recibidos.component').then(m => m.CrearPagosRecibidosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'estudiantes.pagos.administrar' } },
  { path: 'estudiantes/pagos/:id', loadComponent: () => import('./components/estudiantes/pagos/pagos-recibidos.component').then(m => m.PagosRecibidosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'estudiantes.pagos' } },
  { path: 'estudiantes/productos-servicios/:accion/:id/:idEstudiante', loadComponent: () => import('./components/estudiantes/productos-servicios/crear-productos-servicios/crear-productos-servicios.component').then(m => m.CrearProductosServiciosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'estudiantes.productos_servicios.administrar' } },
  { path: 'estudiantes/productos-servicios/:id', loadComponent: () => import('./components/estudiantes/productos-servicios/productos-servicios.component').then(m => m.ProductosServiciosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'estudiantes.productos_servicios' } },
  { path: 'estudiantes/servicios/:accion/:id/:idEstudiante', loadComponent: () => import('./components/servicios/administrar-servicios-estudiante/administrar-servicios-estudiante.component').then(m => m.AdministrarServiciosEstudianteComponent), canActivate: [AuthGuard] },
  { path: 'estudiantes/servicios/:id', loadComponent: () => import('./components/servicios/servicios/servicios.component').then(m => m.ServiciosComponent), canActivate: [AuthGuard] },
  { path: 'estudiantes/vista/:id', loadComponent: () => import('./components/estudiantes/vista-estudiante/vista-estudiante.component').then(m => m.VistaEstudianteComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'estudiantes.vista_360' } },
  { path: 'estudiantes/:accion/:id', loadComponent: () => import('./components/estudiantes/crear-estudiante/crear-estudiante.component').then(m => m.CrearEstudianteComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'estudiantes.administrar' } },

  // ==================================================================
  // Académico
  // ==================================================================
  { path: 'academico/actividades/evaluacion', loadComponent: () => import('./components/academico/crear-actividades-evaluacion/crear-actividades-evaluacion.component').then(m => m.CrearActividadesEvaluacionComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.actividades_evaluacion', trackear: true, labelAcceso: 'Actividades de Evaluación', iconoAcceso: '🎯' } },
  { path: 'academico/actividades/gestion', loadComponent: () => import('./components/academico/actividades/actividades-academicas.component').then(m => m.ActividadesAcademicasComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.actividades', trackear: true, labelAcceso: 'Actividades Académicas', iconoAcceso: '📝' } },
  { path: 'academico/actividades/importar', loadComponent: () => import('./components/academico/importar-actividades-sprint/importar-actividades-sprint.component').then(m => m.ImportarActividadesSprintComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.importar_actividades_sprint', trackear: true, labelAcceso: 'Importar de Sprint', iconoAcceso: '📋' } },
  { path: 'academico/actividades/manual', loadComponent: () => import('./components/academico/crear-actividades-manual/crear-actividades-manual.component').then(m => m.CrearActividadesManualComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.crear_actividades_manual', trackear: true, labelAcceso: 'Crear Actividades Manual', iconoAcceso: '✏️' } },
  { path: 'academico/actividades/maquina', loadComponent: () => import('./components/academico/maquina-actividades/maquina-actividades.component').then(m => m.MaquinaActividadesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.maquina_actividades', trackear: true, labelAcceso: 'Máquina Actividades', iconoAcceso: '🤖' } },
  { path: 'academico/actividades', loadComponent: () => import('./components/academico/selector-actividades/selector-actividades.component').then(m => m.SelectorActividadesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.selector_actividades', trackear: true, labelAcceso: 'Selector Actividades', iconoAcceso: '🎯' } },
  { path: 'academico/areas-academicas', loadComponent: () => import('./components/academico/areas-academicas/areas-academicas.component').then(m => m.AreasAcademicasComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.areas_academicas', trackear: true, labelAcceso: 'Áreas Académicas', iconoAcceso: '📖' } },
  { path: 'academico/clases-ia', loadComponent: () => import('./components/clases-ia/clases-ia.component').then(m => m.ClasesIaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.clases_ia', trackear: true, labelAcceso: 'Clases IA', iconoAcceso: '🤖' } },
  { path: 'academico/cortes-academicos', loadComponent: () => import('./components/academico/cortes-academicos/cortes-academicos.component').then(m => m.CortesAcademicosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.cortes_academicos', trackear: true, labelAcceso: 'Cortes Académicos', iconoAcceso: '📅' } },
  { path: 'academico/cursos-extra', loadComponent: () => import('./components/academico/cursos-extra/cursos-extra.component').then(m => m.CursosExtraComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.cursos_extra', trackear: true, labelAcceso: 'Cursos Extracurriculares', iconoAcceso: '🎭' } },
  { path: 'academico/grados', loadComponent: () => import('./components/academico/grados/grados.component').then(m => m.GradosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.grados', trackear: true, labelAcceso: 'Grados', iconoAcceso: '📚' } },
  { path: 'academico/grupos', loadComponent: () => import('./components/academico/grupos/grupos.component').then(m => m.GruposComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.grupos', trackear: true, labelAcceso: 'Grupos', iconoAcceso: '👨‍👩‍👧‍👦' } },
  { path: 'academico/indicadores-logros', loadComponent: () => import('./components/academico/indicadores-logros/indicadores-logros.component').then(m => m.IndicadoresLogrosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.indicadores_logros', trackear: true, labelAcceso: 'Indicadores Logros', iconoAcceso: '🎯' } },
  { path: 'academico/logros', loadComponent: () => import('./components/academico/logros/logros.component').then(m => m.LogrosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.logros', trackear: true, labelAcceso: 'Logros', iconoAcceso: '🏆' } },
  { path: 'academico/parametros-calificaciones', loadComponent: () => import('./components/academico/parametros-calificaciones/parametros-calificaciones.component').then(m => m.ParametrosCalificacionesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.parametros_calificaciones', trackear: true, labelAcceso: 'Parámetros Calificaciones', iconoAcceso: '⚙️' } },
  { path: 'academico/pde-items', loadComponent: () => import('./components/academico/pde-items/pde-items.component').then(m => m.PdeItemsComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.pde_items', trackear: true, labelAcceso: 'Ítems Perfil Desarrollo', iconoAcceso: '🧩' } },
  { path: 'academico/pde-rangos-edad', loadComponent: () => import('./components/academico/pde-rangos-edad/pde-rangos-edad.component').then(m => m.PdeRangosEdadComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.pde_rangos_edad', trackear: true, labelAcceso: 'Rangos de Edad PDE', iconoAcceso: '📏' } },
  { path: 'academico/sprints', loadComponent: () => import('./components/academico/sprints/sprints.component').then(m => m.SprintsComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.sprints', trackear: true, labelAcceso: 'Sprints', iconoAcceso: '🏃' } },
  { path: 'academico', loadComponent: () => import('./components/academico/academico/academico.component').then(m => m.AcademicoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.ver', trackear: true, labelAcceso: 'Académico', iconoAcceso: '🎓' } },
  { path: 'academico/actividades/gestion/:accion/:id', loadComponent: () => import('./components/academico/actividades/crear-actividades/crear-actividades-academicas.component').then(m => m.CrearActividadesAcademicasComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.actividades' } },
  { path: 'academico/clases-ia/gini-ingles/:idGrupo', loadComponent: () => import('./components/clases-ia/gini-ingles/gini-ingles.component').then(m => m.GiniInglesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.clases_ia' } },
  { path: 'academico/sprints/configurar/:id', loadComponent: () => import('./components/academico/sprints/configurar-sprint/configurar-sprint.component').then(m => m.ConfigurarSprintComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.sprints' } },
  { path: 'academico/areas-academicas/:accion/:id', loadComponent: () => import('./components/academico/areas-academicas/crear-area-academica/crear-area-academica.component').then(m => m.CrearAreaAcademicaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.areas_academicas' } },
  { path: 'academico/cortes-academicos/:accion/:id', loadComponent: () => import('./components/academico/cortes-academicos/crear-corte-academico/crear-corte-academico.component').then(m => m.CrearCorteAcademicoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.cortes_academicos' } },
  { path: 'academico/cursos-extra/:accion/:id', loadComponent: () => import('./components/academico/cursos-extra/crear-curso-extra/crear-curso-extra.component').then(m => m.CrearCursoExtraComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.cursos_extra' } },
  { path: 'academico/grados/:accion/:id', loadComponent: () => import('./components/academico/grados/crear-grado/crear-grado.component').then(m => m.CrearGradoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.grados' } },
  { path: 'academico/grupos/:accion/:id', loadComponent: () => import('./components/academico/grupos/crear-grupo/crear-grupo.component').then(m => m.CrearGrupoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.grupos' } },
  { path: 'academico/indicadores-logros/:accion/:id', loadComponent: () => import('./components/academico/indicadores-logros/editar-indicadores-logros/editar-indicadores-logros.component').then(m => m.EditarIndicadoresLogrosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.indicadores_logros' } },
  { path: 'academico/logros/:accion/:id', loadComponent: () => import('./components/academico/logros/crear-logros/crear-logros.component').then(m => m.CrearLogrosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.logros' } },
  { path: 'academico/parametros-calificaciones/:accion/:id', loadComponent: () => import('./components/academico/parametros-calificaciones/crear-parametro-calificaciones/crear-parametro-calificaciones.component').then(m => m.CrearParametroCalificacionesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.parametros_calificaciones' } },
  { path: 'academico/pde-items/:accion/:id', loadComponent: () => import('./components/academico/pde-items/crear-pde-item/crear-pde-item.component').then(m => m.CrearPdeItemComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.pde_items' } },
  { path: 'academico/pde-rangos-edad/:accion/:id', loadComponent: () => import('./components/academico/pde-rangos-edad/crear-pde-rango-edad/crear-pde-rango-edad.component').then(m => m.CrearPdeRangoEdadComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.pde_rangos_edad' } },
  { path: 'academico/sprints/:accion/:id', loadComponent: () => import('./components/academico/sprints/crear-sprints/crear-sprints.component').then(m => m.CrearSprintsComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'academico.sprints' } },

  // ==================================================================
  // Calificaciones
  // ==================================================================
  {
    path: 'calificacion',
    loadComponent: () => import('./components/calificacion/calificacion.component').then(m => m.CalificacionComponent),
    canActivate: [AuthGuard, PermisosGuard],
    data: { permiso: 'calificaciones.ver', trackear: true, labelAcceso: 'Calificaciones', iconoAcceso: '⭐' },
    children: [
      { path: '', loadComponent: () => import('./components/calificacion/selector-grupos/selector-grupos.component').then(m => m.SelectorGruposComponent) },
      { path: 'grupo/:idGrupo', loadComponent: () => import('./components/calificacion/selector-areas/selector-areas.component').then(m => m.SelectorAreasComponent), data: { trackear: true, labelAcceso: 'Áreas del Grupo', iconoAcceso: '📚' } },
      { path: 'grupo/:idGrupo/area/:idArea', loadComponent: () => import('./components/calificacion/lista-actividades/lista-actividades.component').then(m => m.ListaActividadesComponent) },
      { path: 'grupo/:idGrupo/area/:idArea/actividad/:idTareaSprint', loadComponent: () => import('./components/calificacion/calificacion-estudiantes/calificacion-estudiantes.component').then(m => m.CalificacionEstudiantesComponent) }
    ]
  },

  // ==================================================================
  // Asistencia
  // ==================================================================
  { path: 'asistencia', loadComponent: () => import('./components/asistencia/asistencia.component').then(m => m.AsistenciaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'asistencia.ver', trackear: true, labelAcceso: 'Asistencia', iconoAcceso: '✋' } },

  // ==================================================================
  // Reportes
  // ==================================================================
  { path: 'reportes/calificaciones/estudiante', loadComponent: () => import('./components/reportes/calificaciones-estudiante-detalle/calificaciones-estudiante-detalle.component').then(m => m.CalificacionesEstudianteDetalleComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'reportes.calificaciones_estudiante', trackear: true, labelAcceso: 'Calificaciones Estudiante', iconoAcceso: '🎯' } },
  { path: 'reportes/academicos-estudiante', loadComponent: () => import('./components/reportes/reportes-academicos-estudiante/reportes-academicos-estudiante.component').then(m => m.ReportesAcademicosEstudianteComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'reportes.academicos_estudiante', trackear: true, labelAcceso: 'Reportes Académicos', iconoAcceso: '📄' } },
  { path: 'reportes/alimentacion', loadComponent: () => import('./components/reportes/alimentacion/reporte-alimentacion.component').then(m => m.ReporteAlimentacionComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'reportes.alimentacion', trackear: true, labelAcceso: 'Reporte Alimentación', iconoAcceso: '🍎' } },
  { path: 'reportes/asistencia', loadComponent: () => import('./components/reportes/reporte-asistencia/reporte-asistencia.component').then(m => m.ReporteAsistenciaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'reportes.asistencia', trackear: true, labelAcceso: 'Reporte Asistencia', iconoAcceso: '✋' } },
  { path: 'reportes/asistencia-colaboradores', loadComponent: () => import('./components/reportes/reporte-asistencia-colaboradores/reporte-asistencia-colaboradores.component').then(m => m.ReporteAsistenciaColaboradoresComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'reportes.asistencia_colaboradores', trackear: true, labelAcceso: 'Asistencia Colaboradores', iconoAcceso: '📋' } },
  { path: 'reportes/calificaciones-pdm', loadComponent: () => import('./components/reportes/consultar-calificaciones-pdm-x-estudiantes/consultar-calificaciones-pdm-x-estudiantes.component').then(m => m.ConsultarCalificacionesPdmXEstudiantesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'reportes.calificaciones_pdm', trackear: true, labelAcceso: 'Calificaciones PDM', iconoAcceso: '📝' } },
  { path: 'reportes/calificaciones-sprint', loadComponent: () => import('./components/reportes/calificaciones-sprint-estudiantes/calificaciones-sprint-estudiantes.component').then(m => m.CalificacionesSprintEstudiantesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'reportes.calificaciones_sprint', trackear: true, labelAcceso: 'Calificaciones Sprint', iconoAcceso: '📝' } },
  { path: 'reportes/cartera', loadComponent: () => import('./components/reportes/reporte-cartera/reporte-cartera.component').then(m => m.ReporteCarteraComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'reportes.cartera', trackear: true, labelAcceso: 'Reporte Cartera', iconoAcceso: '💰' } },
  { path: 'reportes/cobertura-curricular', loadComponent: () => import('./components/reportes/reporte-cobertura-curricular/reporte-cobertura-curricular.component').then(m => m.ReporteCoberturaCurricularComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'reportes.cobertura_curricular', trackear: true, labelAcceso: 'Cobertura Curricular', iconoAcceso: '📈' } },
  { path: 'reportes/cobros-realizados', loadComponent: () => import('./components/reportes/reporte-cobros/reporte-cobros.component').then(m => m.ReporteCobrosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'reportes.cobros_realizados', trackear: true, labelAcceso: 'Cobros Realizados', iconoAcceso: '🧾' } },
  { path: 'reportes/cursos-extra', loadComponent: () => import('./components/reportes/reporte-cursos-extra/reporte-cursos-extra.component').then(m => m.ReporteCursosExtraComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'reportes.cursos_extra', trackear: true, labelAcceso: 'Reporte Cursos Extra', iconoAcceso: '🎭' } },
  { path: 'reportes/dashboard-gerencial', loadComponent: () => import('./components/reportes/dashboard-gerencial/dashboard-gerencial.component').then(m => m.DashboardGerencialComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'dashboard.gerencial.listado', trackear: true, labelAcceso: 'Dashboard Gerencial', iconoAcceso: '📊' } },
  { path: 'reportes/ejecucion-tareas', loadComponent: () => import('./components/reportes/reporte-ejecucion-tareas/reporte-ejecucion-tareas.component').then(m => m.ReporteEjecucionTareasComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'reportes.ejecucion_tareas', trackear: true, labelAcceso: 'Ejecución de Tareas', iconoAcceso: '📊' } },
  { path: 'reportes/estudiantes-general', loadComponent: () => import('./components/reportes/reporte-estudiantes/reporte-estudiantes.component').then(m => m.ReporteEstudiantesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'reportes.estudiantes_general', trackear: true, labelAcceso: 'Reporte Estudiantes', iconoAcceso: '📋' } },
  { path: 'reportes/historial-actividades', loadComponent: () => import('./components/reportes/historial-actividades/historial-actividades.component').then(m => m.HistorialActividadesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'reportes.historial_actividades', trackear: true, labelAcceso: 'Historial Actividades', iconoAcceso: '📜' } },
  { path: 'reportes/malla-curricular', loadComponent: () => import('./components/reportes/reporte-malla-curricular/reporte-malla-curricular.component').then(m => m.ReporteMallaCurricularComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'reportes.malla_curricular', trackear: true, labelAcceso: 'Malla Curricular', iconoAcceso: '🗺️' } },
  { path: 'reportes/monitoreo-sprint', loadComponent: () => import('./components/reportes/monitoreo-sprint/monitoreo-sprint.component').then(m => m.MonitoreoSprintComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'reportes.monitoreo_sprint', trackear: true, labelAcceso: 'Monitoreo Sprint', iconoAcceso: '🏃' } },
  { path: 'reportes/movimientos-financieros', loadComponent: () => import('./components/reportes/reporte-movimientos-financieros/reporte-movimientos-financieros.component').then(m => m.ReporteMovimientosFinancierosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'reportes.movimientos_financieros', trackear: true, labelAcceso: 'Ingresos y Egresos', iconoAcceso: '💹' } },
  { path: 'reportes/pagos-recibidos', loadComponent: () => import('./components/reportes/reporte-pagos-recibidos/reporte-pagos-recibidos.component').then(m => m.ReportePagosRecibidosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'reportes.pagos_recibidos', trackear: true, labelAcceso: 'Reporte Pagos', iconoAcceso: '💳' } },
  { path: 'reportes/reporte-contabilizaciones', loadComponent: () => import('./components/reportes/reporte-contabilizaciones/reporte-contabilizaciones.component').then(m => m.ReporteContabilizacionesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'reportes.contabilizaciones', trackear: true, labelAcceso: 'Reporte Contabilizaciones', iconoAcceso: '🧾' } },
  { path: 'reportes/reportes-pago', loadComponent: () => import('./components/reportes/reporte-reportes-pago/reporte-reportes-pago.component').then(m => m.ReporteReportesPagoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'reportes.reportes_pago', trackear: true, labelAcceso: 'Reportes de Pago', iconoAcceso: '📑' } },
  { path: 'reportes', loadComponent: () => import('./components/reportes/reportes.component').then(m => m.ReportesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'reportes.ver', trackear: true, labelAcceso: 'Reportes', iconoAcceso: '📊' } },
  { path: 'reportes/calificacion-pdm-estudiante/:id', loadComponent: () => import('./components/reportes/consultar-calificaciones-pdm-x-estudiante/consultar-calificaciones-pdm-x-estudiante.component').then(m => m.ConsultarCalificacionesPdmXEstudianteComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'reportes.calificaciones_pdm' } },

  // ==================================================================
  // Operaciones
  // ==================================================================
  { path: 'operaciones/actualizacion-datos-estudiantes', loadComponent: () => import('./components/operaciones/actualizacion-datos-estudiantes/actualizacion-datos-estudiantes.component').then(m => m.ActualizacionDatosEstudiantesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.actualizacion_datos', trackear: true, labelAcceso: 'Actualización Datos', iconoAcceso: '🔄' } },
  { path: 'operaciones/asignacion-onces', loadComponent: () => import('./components/operaciones/asignacion-onces/asignacion-onces.component').then(m => m.AsignacionOncesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.asignacion_onces', trackear: true, labelAcceso: 'Asignación de Onces', iconoAcceso: '🍱' } },
  { path: 'operaciones/disponibilidad-cocina', loadComponent: () => import('./components/operaciones/disponibilidad-cocina/disponibilidad-cocina.component').then(m => m.DisponibilidadCocinaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.disponibilidad_cocina', trackear: true, labelAcceso: 'Disponibilidad Cocina', iconoAcceso: '🍳' } },
  { path: 'operaciones/edicion-masiva-limpieza', loadComponent: () => import('./components/operaciones/registros-limpieza/edicion-masiva-limpieza/edicion-masiva-limpieza.component').then(m => m.EdicionMasivaLimpiezaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.edicion_masiva_limpieza', trackear: true, labelAcceso: 'Edición Masiva de Aseo', iconoAcceso: '✏️' } },
  { path: 'operaciones/entrega-alimentacion', loadComponent: () => import('./components/operaciones/entrega-alimentacion/entrega-alimentacion.component').then(m => m.EntregaAlimentacionComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.entrega_alimentacion', trackear: true, labelAcceso: 'Entrega Alimentación', iconoAcceso: '🍽️' } },
  { path: 'operaciones/evaluacion-desarrollo', loadComponent: () => import('./components/operaciones/evaluacion-desarrollo/evaluacion-desarrollo.component').then(m => m.EvaluacionDesarrolloComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.evaluacion_desarrollo', trackear: true, labelAcceso: 'Evaluación Desarrollo', iconoAcceso: '📈' } },
  { path: 'operaciones/galerias', loadComponent: () => import('./components/operaciones/galerias/galerias.component').then(m => m.GaleriasComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.galerias', trackear: true, labelAcceso: 'Galerías', iconoAcceso: '🖼️' } },
  { path: 'operaciones/inscripcion-cursos-extra', loadComponent: () => import('./components/operaciones/inscripcion-cursos-extra/inscripcion-cursos-extra.component').then(m => m.InscripcionCursosExtraComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.inscripcion_cursos_extra', trackear: true, labelAcceso: 'Inscripción Cursos Extra', iconoAcceso: '🎭' } },
  { path: 'operaciones/inventario-alimentacion', loadComponent: () => import('./components/operaciones/inventario-alimentacion/inventario-alimentacion.component').then(m => m.InventarioAlimentacionComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.inventario_alimentacion', trackear: true, labelAcceso: 'Inventario Alimentación', iconoAcceso: '📦' } },
  { path: 'operaciones/movimientos-productos', loadComponent: () => import('./components/operaciones/movimientos-productos/movimientos-productos.component').then(m => m.MovimientosProductosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.movimientos_productos', trackear: true, labelAcceso: 'Movimientos Productos', iconoAcceso: '📦' } },
  { path: 'operaciones/observaciones-informe', loadComponent: () => import('./components/operaciones/registro-observaciones-informe/registro-observaciones-informe.component').then(m => m.RegistroObservacionesInformeComponent), canActivate: [AuthGuard, PermisosGuard], data: { trackear: true, labelAcceso: 'Observaciones para Informe', iconoAcceso: '📝', permiso: 'estudiantes.observaciones.administrar' } },
  { path: 'operaciones/perfil-desarrollo', loadComponent: () => import('./components/operaciones/perfil-desarrollo/perfil-desarrollo.component').then(m => m.PerfilDesarrolloComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.perfil_desarrollo', trackear: true, labelAcceso: 'Perfil de Desarrollo', iconoAcceso: '🧠' } },
  { path: 'operaciones/recordatorio-pagos', loadComponent: () => import('./components/operaciones/recordatorio-pagos/recordatorio-pagos.component').then(m => m.RecordatorioPagosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.recordatorio_pagos', trackear: true, labelAcceso: 'Recordatorio Pagos', iconoAcceso: '💬' } },
  { path: 'operaciones/recordatorios-generales', loadComponent: () => import('./components/operaciones/recordatorios-generales/recordatorios-generales.component').then(m => m.RecordatoriosGeneralesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.recordatorios_generales', trackear: true, labelAcceso: 'Recordatorios Generales', iconoAcceso: '📢' } },
  { path: 'operaciones/registro-masivo-limpieza', loadComponent: () => import('./components/operaciones/registros-limpieza/registro-masivo-limpieza/registro-masivo-limpieza.component').then(m => m.RegistroMasivoLimpiezaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.registro_masivo_limpieza', trackear: true, labelAcceso: 'Registro Masivo de Aseo', iconoAcceso: '📅' } },
  { path: 'operaciones/registro-medidas', loadComponent: () => import('./components/operaciones/registro-medidas/registro-medidas.component').then(m => m.RegistroMedidasComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.registro_medidas', trackear: true, labelAcceso: 'Registro Medidas', iconoAcceso: '📏' } },
  { path: 'operaciones/registro-rapido-limpieza', loadComponent: () => import('./components/operaciones/registros-limpieza/registro-rapido-limpieza/registro-rapido-limpieza.component').then(m => m.RegistroRapidoLimpiezaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.registro_rapido_limpieza', trackear: true, labelAcceso: 'Registro Rápido de Aseo', iconoAcceso: '⚡' } },
  { path: 'operaciones/registros-limpieza', loadComponent: () => import('./components/operaciones/registros-limpieza/registros-limpieza.component').then(m => m.RegistrosLimpiezaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.registros_limpieza', trackear: true, labelAcceso: 'Registros Limpieza', iconoAcceso: '🧼' } },
  { path: 'operaciones/reporte-aseo', loadComponent: () => import('./components/operaciones/registros-limpieza/reporte-aseo/reporte-aseo.component').then(m => m.ReporteAseoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.reporte_aseo', trackear: true, labelAcceso: 'Reporte de Aseo', iconoAcceso: '📄' } },
  { path: 'operaciones/salidas-alimentacion', loadComponent: () => import('./components/operaciones/salidas-alimentacion/salidas-alimentacion.component').then(m => m.SalidasAlimentacionComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.salidas_alimentacion', trackear: true, labelAcceso: 'Salidas Alimentación', iconoAcceso: '🍱' } },
  { path: 'operaciones/seguimiento-asistencia', loadComponent: () => import('./components/operaciones/seguimiento-asistencia/seguimiento-asistencia.component').then(m => m.SeguimientoAsistenciaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.seguimiento_asistencia', trackear: true, labelAcceso: 'Seguimiento Asistencia', iconoAcceso: '📋' } },
  { path: 'operaciones/supervision-limpieza', loadComponent: () => import('./components/operaciones/registros-limpieza/supervision-limpieza/supervision-limpieza.component').then(m => m.SupervisionLimpiezaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.supervision_limpieza', trackear: true, labelAcceso: 'Supervisión de Aseo', iconoAcceso: '✅' } },
  { path: 'operaciones/notificaciones-envio', loadComponent: () => import('./components/operaciones/notificaciones-envio/notificaciones-envio.component').then(m => m.NotificacionesEnvioComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.notificaciones_envio', trackear: true, labelAcceso: 'Envío de Notificaciones', iconoAcceso: '📨' } },
  { path: 'operaciones/notificaciones-envio/:accion/:id', loadComponent: () => import('./components/operaciones/notificaciones-envio/crear-notificacion/crear-notificacion.component').then(m => m.CrearNotificacionComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.notificaciones_envio' } },
  { path: 'operaciones/notificaciones-monitoreo', loadComponent: () => import('./components/operaciones/notificaciones-monitoreo/notificaciones-monitoreo.component').then(m => m.NotificacionesMonitoreoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.notificaciones_monitoreo', trackear: true, labelAcceso: 'Monitoreo de Notificaciones', iconoAcceso: '📊' } },
  { path: 'operaciones', loadComponent: () => import('./components/operaciones/operaciones.component').then(m => m.OperacionesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.ver', trackear: true, labelAcceso: 'Operaciones', iconoAcceso: '⚙️' } },
  { path: 'operaciones/evaluacion-desarrollo/evaluar/:idEstudiante', loadComponent: () => import('./components/operaciones/evaluacion-desarrollo/evaluar-estudiante/evaluar-estudiante.component').then(m => m.EvaluarEstudianteComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.evaluacion_desarrollo' } },
  { path: 'operaciones/evaluacion-desarrollo/historial/:idEstudiante', loadComponent: () => import('./components/operaciones/evaluacion-desarrollo/historial-evaluaciones/historial-evaluaciones.component').then(m => m.HistorialEvaluacionesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.evaluacion_desarrollo' } },
  { path: 'operaciones/galerias/imagenes/:id', loadComponent: () => import('./components/operaciones/galerias/gestionar-imagenes/gestionar-imagenes.component').then(m => m.GestionarImagenesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.galerias' } },
  { path: 'operaciones/movimientos-productos/comprobante/:id', loadComponent: () => import('./components/operaciones/movimientos-productos/movimiento-comprobante/movimiento-comprobante.component').then(m => m.MovimientoComprobanteComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.movimientos_productos' } },
  { path: 'operaciones/perfil-desarrollo/aplicar/:idEstudiante', loadComponent: () => import('./components/operaciones/perfil-desarrollo/aplicar-perfil/aplicar-perfil.component').then(m => m.AplicarPerfilComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.perfil_desarrollo' } },
  { path: 'operaciones/perfil-desarrollo/historial/:idEstudiante', loadComponent: () => import('./components/operaciones/perfil-desarrollo/historial-perfil/historial-perfil.component').then(m => m.HistorialPerfilComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.perfil_desarrollo' } },
  { path: 'operaciones/galerias/:accion/:id', loadComponent: () => import('./components/operaciones/galerias/crear-galeria/crear-galeria.component').then(m => m.CrearGaleriaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.galerias' } },
  { path: 'operaciones/movimientos-productos/:accion/:id', loadComponent: () => import('./components/operaciones/movimientos-productos/crear-movimientos/crear-movimiento-producto.component').then(m => m.CrearMovimientoProductoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.movimientos_productos' } },
  { path: 'operaciones/registros-limpieza/:accion/:id', loadComponent: () => import('./components/operaciones/registros-limpieza/crear-registro-limpieza/crear-registro-limpieza.component').then(m => m.CrearRegistroLimpiezaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.registros_limpieza' } },
  { path: 'operaciones/salidas-alimentacion/:accion/:id', loadComponent: () => import('./components/operaciones/salidas-alimentacion/crear-salida/crear-salida-alimentacion.component').then(m => m.CrearSalidaAlimentacionComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.salidas_alimentacion' } },

  // ==================================================================
  // Colaboradores
  // ==================================================================
  { path: 'colaboradores/actividades/aprobacion', loadComponent: () => import('./components/colaboradores/actividades-colaboradores/aprobacion-actividades-colaboradores/aprobacion-actividades-colaboradores.component').then(m => m.AprobacionActividadesColaboradoresComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'colaboradores.aprobacion_actividades', trackear: true, labelAcceso: 'Aprobación Actividades', iconoAcceso: '✅' } },
  { path: 'colaboradores/actividades/calendario', loadComponent: () => import('./components/colaboradores/actividades-colaboradores/calendario-colaboradores/calendario-colaboradores.component').then(m => m.CalendarioColaboradoresComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'colaboradores.calendario', trackear: true, labelAcceso: 'Calendario Colaboradores', iconoAcceso: '📅' } },
  { path: 'colaboradores/actividades/contabilizacion', loadComponent: () => import('./components/colaboradores/actividades-colaboradores/contabilizacion-actividades-colaboradores/contabilizacion-actividades-colaboradores.component').then(m => m.ContabilizacionActividadesColaboradoresComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'colaboradores.contabilizacion_actividades', trackear: true, labelAcceso: 'Contabilización Actividades', iconoAcceso: '🧮' } },
  { path: 'colaboradores/actividades', loadComponent: () => import('./components/colaboradores/actividades-colaboradores/actividades-colaboradores.component').then(m => m.ActividadesColaboradoresComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'colaboradores.actividades', trackear: true, labelAcceso: 'Actividades Colaboradores', iconoAcceso: '📋' } },
  { path: 'colaboradores/gestion', loadComponent: () => import('./components/colaboradores/gestion-colaboradores/gestion-colaboradores.component').then(m => m.GestionColaboradoresComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'colaboradores.gestion', trackear: true, labelAcceso: 'Gestión Colaboradores', iconoAcceso: '👥' } },
  { path: 'colaboradores/nominas', loadComponent: () => import('./components/colaboradores/nominas/nominas.component').then(m => m.NominasComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'colaboradores.nominas', trackear: true, labelAcceso: 'Nóminas', iconoAcceso: '💰' } },
  { path: 'colaboradores', loadComponent: () => import('./components/colaboradores/colaboradores.component').then(m => m.ColaboradoresComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'colaboradores.listado', trackear: true, labelAcceso: 'Colaboradores', iconoAcceso: '🧑‍💼' } },
  { path: 'colaboradores/pagos-recibidos/comprobante/:id', loadComponent: () => import('./components/colaboradores/pagos-recibidos/comprobante-pago-colaborador-view/comprobante-pago-colaborador-view.component').then(m => m.ComprobantePagoColaboradorViewComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'colaboradores.listado' } },
  { path: 'colaboradores/prestamos-pagos/crear/:idPrestamo/:idColaborador', loadComponent: () => import('./components/colaboradores/prestamos/colaboradores-prestamos-pagos/crear-colaboradores-prestamos-pagos.component').then(m => m.CrearColaboradoresPrestamosPagosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'colaboradores.listado' } },
  { path: 'colaboradores/asistencia/:id', loadComponent: () => import('./components/colaboradores/asistencia-colaborador/asistencia-colaborador.component').then(m => m.AsistenciaColaboradorComponent), canActivate: [AuthGuard] },
  { path: 'colaboradores/contratos/:accion/:id/:idColaborador', loadComponent: () => import('./components/colaboradores/contratos-colaborador/crear-contrato-colaborador/crear-contrato-colaborador.component').then(m => m.CrearContratoColaboradorComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'colaboradores.contratos.administrar' } },
  { path: 'colaboradores/contratos/:id', loadComponent: () => import('./components/colaboradores/contratos-colaborador/contratos-colaborador.component').then(m => m.ContratosColaboradorComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'colaboradores.contratos' } },
  { path: 'colaboradores/gestion-tiempo/:id', loadComponent: () => import('./components/colaboradores/gestion-tiempo-colaborador/gestion-tiempo-colaborador.component').then(m => m.GestionTiempoColaboradorComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'colaboradores.listado' } },
  { path: 'colaboradores/nominas/:accion/:id', loadComponent: () => import('./components/colaboradores/nominas/crear-nomina/crear-nomina.component').then(m => m.CrearNominaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'colaboradores.nominas' } },
  { path: 'colaboradores/opciones/:id', loadComponent: () => import('./components/colaboradores/opciones-colaborador/opciones-colaborador.component').then(m => m.OpcionesColaboradorComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'colaboradores.listado' } },
  { path: 'colaboradores/pagos-recibidos/:accion/:id/:idColaborador', loadComponent: () => import('./components/colaboradores/pagos-recibidos/crear-colaboradores-pagos-recibidos/crear-colaboradores-pagos-recibidos.component').then(m => m.CrearColaboradoresPagosRecibidosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'colaboradores.listado' } },
  { path: 'colaboradores/pagos-recibidos/:id', loadComponent: () => import('./components/colaboradores/pagos-recibidos/colaboradores-pagos-recibidos.component').then(m => m.ColaboradoresPagosRecibidosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'colaboradores.listado' } },
  { path: 'colaboradores/prestamos/:accion/:id/:idColaborador', loadComponent: () => import('./components/colaboradores/prestamos/crear-colaboradores-prestamos/crear-colaboradores-prestamos/crear-colaboradores-prestamos.component').then(m => m.CrearColaboradoresPrestamosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'colaboradores.listado' } },
  { path: 'colaboradores/prestamos/:id', loadComponent: () => import('./components/colaboradores/prestamos/colaboradores-prestamos.component').then(m => m.ColaboradoresPrestamosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'colaboradores.listado' } },
  { path: 'colaboradores/productos-servicios/:accion/:id/:idColaborador', loadComponent: () => import('./components/colaboradores/productos-servicios/crear-colaboradores-productos-servicios/crear-colaboradores-productos-servicios.component').then(m => m.CrearColaboradoresProductosServiciosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'colaboradores.listado' } },
  { path: 'colaboradores/productos-servicios/:id', loadComponent: () => import('./components/colaboradores/productos-servicios/colaboradores-productos-servicios.component').then(m => m.ColaboradoresProductosServiciosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'colaboradores.listado' } },
  { path: 'colaboradores/:accion/:id', loadComponent: () => import('./components/colaboradores/crear-colaboradores/crear-colaboradores.component').then(m => m.CrearColaboradoresComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'colaboradores.listado' } },

  // ==================================================================
  // Administración
  // ==================================================================
  { path: 'administracion', loadComponent: () => import('./components/administracion/administracion/administracion.component').then(m => m.AdministracionComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'administracion.ver', trackear: true, labelAcceso: 'Administración', iconoAcceso: '🏛️' } },

  // ==================================================================
  // Administración / Datos Maestros
  // ==================================================================
  { path: 'administracion/datos-maestros/datos-estudiantes/datos-adicionales', loadComponent: () => import('./components/administracion/datos-estudiantes/datos-adicionales/datos-adicionales-catalogo.component').then(m => m.DatosAdicionalesCatalogoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.datos_estudiantes' } },
  { path: 'administracion/datos-maestros/datos-estudiantes/datos-medicos', loadComponent: () => import('./components/administracion/datos-estudiantes/datos-medicos/datos-medicos-catalogo.component').then(m => m.DatosMedicosCatalogoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.datos_estudiantes' } },
  { path: 'administracion/datos-maestros/datos-estudiantes/tipos-datos-adicionales', loadComponent: () => import('./components/administracion/datos-estudiantes/tipos-datos-adicionales/tipos-datos-adicionales.component').then(m => m.TiposDatosAdicionalesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.datos_estudiantes' } },
  { path: 'administracion/datos-maestros/datos-estudiantes/tipos-datos-medicos', loadComponent: () => import('./components/administracion/datos-estudiantes/tipos-datos-medicos/tipos-datos-medicos.component').then(m => m.TiposDatosMedicosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.datos_estudiantes' } },
  { path: 'administracion/datos-maestros/gestion-medidas/categorias', loadComponent: () => import('./components/administracion/gestion-medidas/categorias-medidas/categorias-medidas.component').then(m => m.CategoriasMedidasComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.categorias_medidas', trackear: true, labelAcceso: 'Categorías Medidas', iconoAcceso: '📏' } },
  { path: 'administracion/datos-maestros/gestion-medidas/medidas', loadComponent: () => import('./components/administracion/gestion-medidas/medidas-catalogo/medidas-catalogo.component').then(m => m.MedidasCatalogoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.catalogo_medidas', trackear: true, labelAcceso: 'Catálogo Medidas', iconoAcceso: '📏' } },
  { path: 'administracion/datos-maestros/gestion-medidas/unidades', loadComponent: () => import('./components/administracion/gestion-medidas/unidades-medidas-corporales/unidades-medidas-corporales.component').then(m => m.UnidadesMedidasCorporalesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.unidades_medidas', trackear: true, labelAcceso: 'Unidades Medidas', iconoAcceso: '📐' } },
  { path: 'administracion/datos-maestros/menus/items', loadComponent: () => import('./components/administracion/menus/items-menu/items-menu.component').then(m => m.ItemsMenuComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.items_menu', trackear: true, labelAcceso: 'Items Menú', iconoAcceso: '🍽️' } },
  { path: 'administracion/datos-maestros/menus/lista', loadComponent: () => import('./components/administracion/menus/lista-menus/lista-menus.component').then(m => m.ListaMenusComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.lista_menus', trackear: true, labelAcceso: 'Lista Menús', iconoAcceso: '📜' } },
  { path: 'administracion/datos-maestros/areas-fisicas', loadComponent: () => import('./components/administracion/areas-fisicas/areas-fisicas.component').then(m => m.AreasFisicasComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.areas_fisicas', trackear: true, labelAcceso: 'Áreas Físicas', iconoAcceso: '🏗️' } },
  { path: 'administracion/datos-maestros/cargos', loadComponent: () => import('./components/administracion/cargos/cargos.component').then(m => m.CargosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.cargos', trackear: true, labelAcceso: 'Cargos', iconoAcceso: '💼' } },
  { path: 'administracion/datos-maestros/conectar-whatsapp', loadComponent: () => import('./components/administracion/conectar-whatsapp/conectar-whatsapp.component').then(m => m.ConectarWhatsappComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.conectar_whatsapp', trackear: true, labelAcceso: 'Conexión WhatsApp', iconoAcceso: '🔌' } },
  { path: 'administracion/datos-maestros/config-aseo', loadComponent: () => import('./components/administracion/config-aseo/config-aseo.component').then(m => m.ConfigAseoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.config_aseo', trackear: true, labelAcceso: 'Configuración de Aseo', iconoAcceso: '🧹' } },
  { path: 'administracion/datos-maestros/configuracion-geofence', loadComponent: () => import('./components/administracion/configuracion-geofence/configuracion-geofence.component').then(m => m.ConfiguracionGeofenceComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.configuracion_geofence', trackear: true, labelAcceso: 'Configuración Geofence', iconoAcceso: '📍' } },
  { path: 'administracion/datos-maestros/configuracion-global', loadComponent: () => import('./components/administracion/configuracion/configuracion-global/configuracion-global.component').then(m => m.ConfiguracionGlobalComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.configuracion_global', trackear: true, labelAcceso: 'Configuración Global', iconoAcceso: '⚙️' } },
  { path: 'administracion/datos-maestros/jornada-laboral', loadComponent: () => import('./components/administracion/jornada-laboral/jornada-laboral.component').then(m => m.JornadaLaboralComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.jornada_laboral', trackear: true, labelAcceso: 'Jornada Laboral', iconoAcceso: '⏰' } },
  { path: 'administracion/datos-maestros/configuracion-google', loadComponent: () => import('./components/administracion/configuracion-google/configuracion-google.component').then(m => m.ConfiguracionGoogleComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.configuracion_google', trackear: true, labelAcceso: 'Configuración Google', iconoAcceso: '📅' } },
  { path: 'administracion/datos-maestros/configuracion-ia', loadComponent: () => import('./components/administracion/configuracion-ia/configuracion-ia.component').then(m => m.ConfiguracionIaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.configuracion_ia', trackear: true, labelAcceso: 'Configuración IA', iconoAcceso: '🤖' } },
  { path: 'administracion/datos-maestros/datos-estudiantes', loadComponent: () => import('./components/administracion/datos-estudiantes/datos-estudiantes.component').then(m => m.DatosEstudiantesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.datos_estudiantes', trackear: true, labelAcceso: 'Datos Estudiantes', iconoAcceso: '🎓' } },
  { path: 'administracion/datos-maestros/documentacion-sistema', loadComponent: () => import('./components/administracion/documentacion-sistema/documentacion-sistema.component').then(m => m.DocumentacionSistemaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.documentacion', trackear: true, labelAcceso: 'Documentación', iconoAcceso: '📖' } },
  { path: 'administracion/datos-maestros/elementos-fisicos', loadComponent: () => import('./components/administracion/elementos-fisicos/elementos-fisicos.component').then(m => m.ElementosFisicosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.elementos_fisicos', trackear: true, labelAcceso: 'Elementos Físicos', iconoAcceso: '🔧' } },
  { path: 'administracion/datos-maestros/gestion-medidas', loadComponent: () => import('./components/administracion/gestion-medidas/gestion-medidas.component').then(m => m.GestionMedidasComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.gestion_medidas', trackear: true, labelAcceso: 'Gestión Medidas', iconoAcceso: '📏' } },
  { path: 'administracion/datos-maestros/institucion', loadComponent: () => import('./components/administracion/institucion/institucion.component').then(m => m.InstitucionComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.institucion', trackear: true, labelAcceso: 'Institución', iconoAcceso: '🏫' } },
  { path: 'administracion/datos-maestros/menus', loadComponent: () => import('./components/administracion/menus/menus.component').then(m => m.MenusComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.menus', trackear: true, labelAcceso: 'Menús', iconoAcceso: '🍽️' } },
  { path: 'administracion/datos-maestros/permisos', loadComponent: () => import('./components/administracion/seguridad/permisos-rol/permisos-rol.component').then(m => m.PermisosRolComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.permisos_rol', trackear: true, labelAcceso: 'Permisos por Rol', iconoAcceso: '🔐' } },
  { path: 'administracion/datos-maestros/usuarios', loadComponent: () => import('./components/administracion/seguridad/gestion-usuarios/gestion-usuarios.component').then(m => m.GestionUsuariosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.usuarios' } },
  { path: 'administracion/datos-maestros/usuarios-x-rol', loadComponent: () => import('./components/administracion/seguridad/usuarios-x-rol/usuarios-x-rol.component').then(m => m.UsuariosXRolComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.usuarios_x_rol' } },
  { path: 'administracion/datos-maestros/roles', loadComponent: () => import('./components/administracion/seguridad/roles/roles.component').then(m => m.RolesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.roles' } },
  { path: 'administracion/datos-maestros/usuarios/:accion/:id', loadComponent: () => import('./components/administracion/seguridad/gestion-usuarios/crear-usuario/crear-usuario.component').then(m => m.CrearUsuarioComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.usuarios' } },
  { path: 'administracion/datos-maestros/roles/:accion/:id', loadComponent: () => import('./components/administracion/seguridad/roles/crear-rol/crear-rol.component').then(m => m.CrearRolComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.roles' } },
  { path: 'administracion/datos-maestros/plantillas', loadComponent: () => import('./components/administracion/configuracion/plantillas/plantillas.component').then(m => m.PlantillasComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.plantillas', trackear: true, labelAcceso: 'Plantillas', iconoAcceso: '📃' } },
  { path: 'administracion/datos-maestros/plantillas-notificaciones', loadComponent: () => import('./components/administracion/plantillas-notificaciones/plantillas-notificaciones.component').then(m => m.PlantillasNotificacionesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.plantillas_notificaciones', trackear: true, labelAcceso: 'Plantillas de Notificaciones', iconoAcceso: '📃' } },
  { path: 'administracion/datos-maestros/plantillas-notificaciones/:accion/:id', loadComponent: () => import('./components/administracion/plantillas-notificaciones/crear-plantilla-notificacion/crear-plantilla-notificacion.component').then(m => m.CrearPlantillaNotificacionComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.plantillas_notificaciones' } },
  { path: 'administracion/datos-maestros/plantillas-whatsapp', loadComponent: () => import('./components/administracion/plantillas-whatsapp/plantillas-whatsapp.component').then(m => m.PlantillasWhatsappComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.plantillas_whatsapp', trackear: true, labelAcceso: 'Plantillas WhatsApp', iconoAcceso: '💬' } },
  { path: 'administracion/datos-maestros/productos', loadComponent: () => import('./components/administracion/productos/productos.component').then(m => m.ProductosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.productos', trackear: true, labelAcceso: 'Productos', iconoAcceso: '📦' } },
  { path: 'administracion/datos-maestros/productos-academico', loadComponent: () => import('./components/administracion/productos-academico/productos-academico.component').then(m => m.ProductosAcademicoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.productos_academico', trackear: true, labelAcceso: 'Productos Académico', iconoAcceso: '📚' } },
  { path: 'administracion/datos-maestros/productos-alimentacion', loadComponent: () => import('./components/administracion/productos-alimentacion/productos-alimentacion.component').then(m => m.ProductosAlimentacionComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.productos_alimentacion', trackear: true, labelAcceso: 'Productos Alimentación', iconoAcceso: '🥗' } },
  { path: 'administracion/datos-maestros/productos-limpieza', loadComponent: () => import('./components/administracion/productos-limpieza/productos-limpieza.component').then(m => m.ProductosLimpiezaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.productos_limpieza', trackear: true, labelAcceso: 'Productos Limpieza', iconoAcceso: '🧹' } },
  { path: 'administracion/datos-maestros/productos-mobiliario', loadComponent: () => import('./components/administracion/productos-mobiliario/productos-mobiliario.component').then(m => m.ProductosMobiliarioComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.productos_mobiliario', trackear: true, labelAcceso: 'Productos Mobiliario', iconoAcceso: '🪑' } },
  { path: 'administracion/datos-maestros/productos-servicios', loadComponent: () => import('./components/administracion/productos-servicios/listar-productos-servicios.component').then(m => m.ListarProductosServiciosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.productos_servicios', trackear: true, labelAcceso: 'Productos y Servicios', iconoAcceso: '🛒' } },
  { path: 'administracion/datos-maestros/proveedores', loadComponent: () => import('./components/administracion/proveedores/proveedores.component').then(m => m.ProveedoresComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.proveedores', trackear: true, labelAcceso: 'Proveedores', iconoAcceso: '🚚' } },
  { path: 'administracion/datos-maestros/tipos-documentos', loadComponent: () => import('./components/administracion/tipos-documentos/tipos-documentos.component').then(m => m.TiposDocumentosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.tipos_documentos', trackear: true, labelAcceso: 'Tipos Documentos', iconoAcceso: '📄' } },
  { path: 'administracion/datos-maestros', loadComponent: () => import('./components/administracion/datos-maestros/datos-maestros.component').then(m => m.DatosMaestrosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'administracion.datos_maestros', trackear: true, labelAcceso: 'Datos Maestros', iconoAcceso: '🗃️' } },
  { path: 'administracion/datos-maestros/datos-estudiantes/datos-adicionales/:accion/:id', loadComponent: () => import('./components/administracion/datos-estudiantes/datos-adicionales/crear-dato-adicional/crear-dato-adicional.component').then(m => m.CrearDatoAdicionalComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.datos_estudiantes' } },
  { path: 'administracion/datos-maestros/datos-estudiantes/datos-medicos/:accion/:id', loadComponent: () => import('./components/administracion/datos-estudiantes/datos-medicos/crear-dato-medico/crear-dato-medico.component').then(m => m.CrearDatoMedicoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.datos_estudiantes' } },
  { path: 'administracion/datos-maestros/datos-estudiantes/tipos-datos-adicionales/:accion/:id', loadComponent: () => import('./components/administracion/datos-estudiantes/tipos-datos-adicionales/crear-tipo-dato-adicional/crear-tipo-dato-adicional.component').then(m => m.CrearTipoDatoAdicionalComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.datos_estudiantes' } },
  { path: 'administracion/datos-maestros/datos-estudiantes/tipos-datos-medicos/:accion/:id', loadComponent: () => import('./components/administracion/datos-estudiantes/tipos-datos-medicos/crear-tipo-dato-medico/crear-tipo-dato-medico.component').then(m => m.CrearTipoDatoMedicoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.datos_estudiantes' } },
  { path: 'administracion/datos-maestros/gestion-medidas/categorias/:accion/:id', loadComponent: () => import('./components/administracion/gestion-medidas/categorias-medidas/crear-categoria-medida/crear-categoria-medida.component').then(m => m.CrearCategoriaMedidaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.categorias_medidas' } },
  { path: 'administracion/datos-maestros/gestion-medidas/medidas/:accion/:id', loadComponent: () => import('./components/administracion/gestion-medidas/medidas-catalogo/crear-medida/crear-medida.component').then(m => m.CrearMedidaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.catalogo_medidas' } },
  { path: 'administracion/datos-maestros/gestion-medidas/unidades/:accion/:id', loadComponent: () => import('./components/administracion/gestion-medidas/unidades-medidas-corporales/crear-unidad-medida/crear-unidad-medida.component').then(m => m.CrearUnidadMedidaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.unidades_medidas' } },
  { path: 'administracion/datos-maestros/menus/items/:accion/:id', loadComponent: () => import('./components/administracion/menus/items-menu/crear-item-menu/crear-item-menu.component').then(m => m.CrearItemMenuComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.items_menu' } },
  { path: 'administracion/datos-maestros/menus/lista/:accion/:id', loadComponent: () => import('./components/administracion/menus/lista-menus/crear-menu/crear-menu.component').then(m => m.CrearMenuComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.lista_menus' } },
  { path: 'administracion/datos-maestros/areas-fisicas/:accion/:id', loadComponent: () => import('./components/administracion/areas-fisicas/crear-area-fisica/crear-area-fisica.component').then(m => m.CrearAreaFisicaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.areas_fisicas' } },
  { path: 'administracion/datos-maestros/cargos/:accion/:id', loadComponent: () => import('./components/administracion/cargos/crear-cargo/crear-cargo.component').then(m => m.CrearCargoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.cargos' } },
  { path: 'administracion/datos-maestros/configuracion-global/:accion/:id', loadComponent: () => import('./components/administracion/configuracion/configuracion-global/editar-configuracion-global/editar-configuracion-global.component').then(m => m.EditarConfiguracionGlobalComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.configuracion_global' } },
  { path: 'administracion/datos-maestros/configuracion-google/:accion/:id', loadComponent: () => import('./components/administracion/configuracion-google/editar-configuracion-google/editar-configuracion-google.component').then(m => m.EditarConfiguracionGoogleComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.configuracion_google' } },
  { path: 'administracion/datos-maestros/configuracion-ia/:accion/:id', loadComponent: () => import('./components/administracion/configuracion-ia/editar-configuracion-ia/editar-configuracion-ia.component').then(m => m.EditarConfiguracionIaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.configuracion_ia' } },
  { path: 'administracion/datos-maestros/elementos-fisicos/:accion/:id', loadComponent: () => import('./components/administracion/elementos-fisicos/crear-elemento-fisico/crear-elemento-fisico.component').then(m => m.CrearElementoFisicoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.elementos_fisicos' } },
  { path: 'administracion/datos-maestros/plantillas/:accion/:id', loadComponent: () => import('./components/administracion/configuracion/plantillas/editar-plantilla/editar-plantilla.component').then(m => m.EditarPlantillaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.plantillas' } },
  { path: 'administracion/datos-maestros/productos-academico/:accion/:id', loadComponent: () => import('./components/administracion/productos-academico/crear-producto-academico/crear-producto-academico.component').then(m => m.CrearProductoAcademicoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.productos_academico' } },
  { path: 'administracion/datos-maestros/productos-alimentacion/:accion/:id', loadComponent: () => import('./components/administracion/productos-alimentacion/crear-productos-alimentacion/crear-producto-alimentacion.component').then(m => m.CrearProductoAlimentacionComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.productos_alimentacion' } },
  { path: 'administracion/datos-maestros/productos-limpieza/:accion/:id', loadComponent: () => import('./components/administracion/productos-limpieza/crear-producto-limpieza/crear-producto-limpieza.component').then(m => m.CrearProductoLimpiezaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.productos_limpieza' } },
  { path: 'administracion/datos-maestros/productos-mobiliario/:accion/:id', loadComponent: () => import('./components/administracion/productos-mobiliario/crear-producto-mobiliario/crear-producto-mobiliario.component').then(m => m.CrearProductoMobiliarioComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.productos_mobiliario' } },
  { path: 'administracion/datos-maestros/productos-servicios/:accion/:id', loadComponent: () => import('./components/administracion/productos-servicios/crear-producto-servicio/crear-producto-servicio.component').then(m => m.CrearProductoServicioComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.productos_servicios' } },
  { path: 'administracion/datos-maestros/productos/:accion/:id', loadComponent: () => import('./components/administracion/productos/crear-producto/crear-producto.component').then(m => m.CrearProductoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.productos' } },
  { path: 'administracion/datos-maestros/proveedores/:accion/:id', loadComponent: () => import('./components/administracion/proveedores/crear-proveedor/crear-proveedor.component').then(m => m.CrearProveedorComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.proveedores' } },
  { path: 'administracion/datos-maestros/tipos-documentos/:accion/:id', loadComponent: () => import('./components/administracion/tipos-documentos/crear-tipo-documento/crear-tipo-documento.component').then(m => m.CrearTipoDocumentoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.tipos_documentos' } },

  // ==================================================================
  // Administración / Financiero
  // ==================================================================
  { path: 'administracion/financiero/aprobacion-multiple', loadComponent: () => import('./components/administracion/aprobacion-multiple-financiero/aprobacion-multiple-financiero.component').then(m => m.AprobacionMultipleFinancieroComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.aprobacion_multiple', trackear: true, labelAcceso: 'Aprobación Múltiple', iconoAcceso: '✅' } },
  { path: 'administracion/financiero/contabilizacion-multiple', loadComponent: () => import('./components/administracion/contabilizacion-multiple/contabilizacion-multiple.component').then(m => m.ContabilizacionMultipleComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.contabilizacion_multiple', trackear: true, labelAcceso: 'Contabilización Múltiple', iconoAcceso: '🧮' } },
  { path: 'administracion/financiero/convenios', loadComponent: () => import('./components/administracion/convenios/convenios.component').then(m => m.ConveniosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.convenios', trackear: true, labelAcceso: 'Convenios', iconoAcceso: '📝' } },
  { path: 'administracion/financiero/movimientos-financieros', loadComponent: () => import('./components/administracion/movimientos-financieros/movimientos-financieros.component').then(m => m.MovimientosFinancierosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.movimientos_financieros', trackear: true, labelAcceso: 'Movimientos Financieros', iconoAcceso: '💸' } },
  { path: 'administracion/financiero/registro-pagos-rapido', loadComponent: () => import('./components/administracion/registro-pagos-rapido/registro-pagos-rapido.component').then(m => m.RegistroPagosRapidoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.registro_pagos_rapido', trackear: true, labelAcceso: 'Registro Pagos Rápido', iconoAcceso: '⚡' } },
  { path: 'administracion/financiero/reglas-cobro-automatico', loadComponent: () => import('./components/administracion/reglas-cobro-automatico/reglas-cobro-automatico.component').then(m => m.ReglasCobroAutomaticoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.reglas_cobro_automatico', trackear: true, labelAcceso: 'Reglas Cobro Automático', iconoAcceso: '⚡' } },
  { path: 'administracion/financiero', loadComponent: () => import('./components/administracion/financiero/financiero.component').then(m => m.FinancieroComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'administracion.financiero', trackear: true, labelAcceso: 'Financiero', iconoAcceso: '💵' } },
  { path: 'administracion/financiero/convenios/:accion/:id', loadComponent: () => import('./components/administracion/convenios/crear-convenio/crear-convenio.component').then(m => m.CrearConvenioComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.convenios' } },
  { path: 'administracion/financiero/movimientos-financieros/:accion/:id', loadComponent: () => import('./components/administracion/movimientos-financieros/crear-movimiento/crear-movimiento.component').then(m => m.CrearMovimientoComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.movimientos_financieros' } },
  { path: 'administracion/financiero/reglas-cobro-automatico/:accion/:id', loadComponent: () => import('./components/administracion/reglas-cobro-automatico/crear-regla-cobro/crear-regla-cobro.component').then(m => m.CrearReglaCobroComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.reglas_cobro_automatico' } },
  { path: 'administracion/financiero/mora-configuracion', loadComponent: () => import('./components/administracion/configuracion-mora/mora-configuracion/mora-configuracion.component').then(m => m.MoraConfiguracionComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.mora_configuracion', trackear: true, labelAcceso: 'Registro Rápido de Mora', iconoAcceso: '⏰' } },
  { path: 'administracion/financiero/mora-exenciones', loadComponent: () => import('./components/administracion/configuracion-mora/mora-exenciones/mora-exenciones.component').then(m => m.MoraExencionesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.mora_exenciones', trackear: true, labelAcceso: 'Registro Rápido de Exenciones', iconoAcceso: '🛡️' } },
  { path: 'administracion/financiero/mora-ejecuciones', loadComponent: () => import('./components/administracion/configuracion-mora/mora-ejecuciones/mora-ejecuciones.component').then(m => m.MoraEjecucionesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.mora_ejecuciones', trackear: true, labelAcceso: 'Proceso de Mora', iconoAcceso: '⚙️' } },

  // ==================================================================
  // Administración / CRM
  // ==================================================================
  { path: 'administracion/crm/contactos-portal', loadComponent: () => import('./components/administracion/crm/contactos-portal/contactos-portal.component').then(m => m.ContactosPortalComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.crm_contactos_portal', trackear: true, labelAcceso: 'Contactos Portal', iconoAcceso: '📞' } },
  { path: 'administracion/crm/dashboard', loadComponent: () => import('./components/administracion/crm/dashboard-crm/dashboard-crm.component').then(m => m.DashboardCrmComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.crm_dashboard', trackear: true, labelAcceso: 'Dashboard CRM', iconoAcceso: '📊' } },
  { path: 'administracion/crm/visitas', loadComponent: () => import('./components/administracion/crm/visitas/visitas.component').then(m => m.VisitasComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.crm_visitas', trackear: true, labelAcceso: 'CRM Visitas', iconoAcceso: '🚶' } },
  { path: 'administracion/crm', loadComponent: () => import('./components/administracion/crm/crm.component').then(m => m.CrmComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'administracion.crm', trackear: true, labelAcceso: 'CRM', iconoAcceso: '🤝' } },
  { path: 'administracion/crm/contactos-portal/:accion/:id', loadComponent: () => import('./components/administracion/crm/contactos-portal/gestionar-contacto-portal/gestionar-contacto-portal.component').then(m => m.GestionarContactoPortalComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.crm_contactos_portal' } },
  { path: 'administracion/crm/visitas/:accion/:id', loadComponent: () => import('./components/administracion/crm/crear-visita/crear-visita.component').then(m => m.CrearVisitaComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.crm_visitas' } },

  // ==================================================================
  // Administración / Operaciones
  // ==================================================================
  { path: 'administracion/operaciones/consulta-entes-control', loadComponent: () => import('./components/administracion/consulta-entes-control/consulta-entes-control.component').then(m => m.ConsultaEntesControlComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.consulta_entes_control', trackear: true, labelAcceso: 'Consulta Entes de Control', iconoAcceso: '🔎' } },
  { path: 'administracion/operaciones/entes-control', loadComponent: () => import('./components/administracion/entes-control/entes-control.component').then(m => m.EntesControlComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.entes_control', trackear: true, labelAcceso: 'Entes de Control', iconoAcceso: '🏛️' } },
  { path: 'administracion/operaciones', loadComponent: () => import('./components/administracion/administracion-operaciones/administracion-operaciones.component').then(m => m.AdministracionOperacionesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'administracion.operaciones', trackear: true, labelAcceso: 'Operaciones', iconoAcceso: '⚙️' } },
  { path: 'administracion/operaciones/utiles-diarios', loadComponent: () => import('./components/administracion/utiles-diarios/utiles-diarios.component').then(m => m.UtilesDiariosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.utiles_diarios', trackear: true, labelAcceso: 'Útiles y Accesorios Diarios', iconoAcceso: '🎒' } },
  { path: 'administracion/operaciones/utiles-diarios/:accion/:id', loadComponent: () => import('./components/administracion/utiles-diarios/crear-util-diario/crear-util-diario.component').then(m => m.CrearUtilDiarioComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.utiles_diarios' } },
  { path: 'operaciones/utiles-diarios', loadComponent: () => import('./components/operaciones/utiles-diarios/registro-utiles-diarios.component').then(m => m.RegistroUtilesDiariosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.utiles_diarios', trackear: true, labelAcceso: 'Útiles y Accesorios Diarios', iconoAcceso: '🎒' } },
  { path: 'reportes/utiles-diarios', loadComponent: () => import('./components/reportes/reporte-utiles-diarios/reporte-utiles-diarios.component').then(m => m.ReporteUtilesDiariosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'reportes.utiles_diarios', trackear: true, labelAcceso: 'Reporte Útiles Diarios', iconoAcceso: '🎒' } },
  { path: 'administracion/operaciones/compromisos', loadComponent: () => import('./components/administracion/tipos-solicitud/tipos-solicitud.component').then(m => m.TiposSolicitudComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.solicitudes_acudientes', trackear: true, labelAcceso: 'Compromisos', iconoAcceso: '📝' } },
  { path: 'administracion/operaciones/compromisos/:accion/:id', loadComponent: () => import('./components/administracion/tipos-solicitud/crear-tipo-solicitud/crear-tipo-solicitud.component').then(m => m.CrearTipoSolicitudComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.solicitudes_acudientes' } },
  { path: 'operaciones/solicitudes-acudientes', loadComponent: () => import('./components/operaciones/solicitudes-acudientes/solicitudes-acudientes.component').then(m => m.SolicitudesAcudientesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.solicitudes_acudientes', trackear: true, labelAcceso: 'Solicitudes de los Padres', iconoAcceso: '📝' } },
  { path: 'operaciones/solicitudes-acudientes/registrar', loadComponent: () => import('./components/operaciones/solicitudes-acudientes/crear-solicitud/crear-solicitud.component').then(m => m.CrearSolicitudJardinComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.solicitudes_acudientes' } },
  { path: 'operaciones/aprobar-solicitudes', loadComponent: () => import('./components/operaciones/aprobar-solicitudes/aprobar-solicitudes.component').then(m => m.AprobarSolicitudesComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.solicitudes_aprobar', trackear: true, labelAcceso: 'Aprobar Solicitudes', iconoAcceso: '✅' } },
  { path: 'operaciones/mis-alertas', loadComponent: () => import('./components/operaciones/notificaciones-colaboradores/notificaciones-colaboradores.component').then(m => m.NotificacionesColaboradoresComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'operaciones.notificaciones_colaboradores', trackear: true, labelAcceso: 'Mis Alertas', iconoAcceso: '🔔' } },
  { path: 'administracion/operaciones/entes-control/:accion/:id', loadComponent: () => import('./components/administracion/entes-control/crear-ente-control/crear-ente-control.component').then(m => m.CrearEnteControlComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.entes_control' } },

  // ==================================================================
  // Administración / Otros
  // ==================================================================
  { path: 'administracion/auditoria-registros', loadComponent: () => import('./components/administracion/auditoria-registros/auditoria-registros.component').then(m => m.AuditoriaRegistrosComponent), canActivate: [AuthGuard, PermisosGuard], data: { permiso: 'admin.auditoria', trackear: true, labelAcceso: 'Auditoría', iconoAcceso: '🔍' } },

  // Ruta comodín
  { path: '**', redirectTo: 'login' }
];